In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
df = pd.read_csv(r"C:\Users\chami\MachineLearning\Machine-Learning\cars24-car-price.csv")

In [10]:
df.head(10)

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto Std,1.20,2012.0,Individual,120000,Petrol,Manual,19.70,796.0,46.30,5.0
1,Hyundai Grand i10 Asta,5.50,2016.0,Individual,20000,Petrol,Manual,18.90,1197.0,82.00,5.0
2,Hyundai i20 Asta,2.15,2010.0,Individual,60000,Petrol,Manual,17.00,1197.0,80.00,5.0
3,Maruti Alto K10 2010-2014 VXI,2.26,2012.0,Individual,37000,Petrol,Manual,20.92,998.0,67.10,5.0
4,Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV,5.70,2015.0,Dealer,30000,Diesel,Manual,22.77,1498.0,98.59,5.0
5,Maruti Wagon R VXI BS IV,3.50,2013.0,Individual,35000,Petrol,Manual,18.90,998.0,67.10,5.0
6,Hyundai i10 Sportz 1.2,3.15,2013.0,Dealer,40000,Petrol,Manual,20.36,1197.0,78.90,5.0
7,Maruti Wagon R VXI,4.10,2018.0,Dealer,17512,Petrol,Manual,20.51,998.0,67.04,5.0
8,Hyundai Venue SX Plus Turbo DCT BSIV,10.50,2019.0,Individual,20000,Petrol,Automatic,18.15,998.0,118.35,5.0
9,Mahindra TUV 300 T6,5.75,2017.0,Dealer,70000,Diesel,Manual,18.49,1493.0,100.00,7.0

In [14]:
df['full_name'].nunique()

3321

In [26]:
df['full_name']  = df.groupby('full_name')['selling_price'].mean()
df['full_name']  = df.groupby('full_name')['selling_price'].mean()